# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://optimizepdx.com
title: Molly O'Brien
email: molly.optimizepdx@gmail.com
author: Molly O'Brien
description: Molly O'Brien provides search engine optimization services for local Portland, Oregon businesses. Molly is also an experienced copywriter who can help Portland businesses have great blog, social media, or meta content. 
copyright: "Copyright &copy; 2018 Molly O'Brien. All Rights Reserved."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    icon: linkedin
    url: https://wwww.linkedin.com/in/molly-o-brien-62882a38
  - title: mail
    icon: mail-reply
    url: mailto:molly.optimizepdx@gmail.com